services:

  api_data:
    build:
      context: src/data
      dockerfile: Dockerfile
    container_name: data_api
    networks: 
      - rakuten_mlops_network
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data              
      - ./models:/app/models          
      - ./config:/app/config:ro       
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  api_train:
    build:
      context: src/train_model
      dockerfile: Dockerfile
    container_name: train_api
    networks: 
      - rakuten_mlops_network
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data:ro           
      - ./models:/app/models          
      - ./config:/app/config:ro 
      - ./results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  api_evaluate:
    build:
      context: src/evaluate_model
      dockerfile: Dockerfile
    container_name: evaluate_api
    networks: 
      - rakuten_mlops_network
    ports:
      - "8004:8004"
    volumes:
      - ./data:/app/data:ro           
      - ./models:/app/models:ro       
      - ./results:/app/results        
      - ./config:/app/config:ro       
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      - MPLBACKEND=Agg

  api_predict:
    build:
      context: src/predict
      dockerfile: Dockerfile
    deploy:
      replicas: 1 # TODO: adjust replicas for production
    container_name: predict_api
    networks: 
      - rakuten_mlops_network
    expose:
      - "8000"
    ports:
      - "8000:8000" # TODO: remove port mapping (visibility from host) for production
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  test_api_predict:
    build: 
      context: tests/test_api_predict
      args:
        LOGDIR: /logs
    container_name: test_api_predict
    depends_on:
      api_predict:
        condition: service_healthy
    networks: 
      - rakuten_mlops_network
    volumes:
      - ./logs:/logs
    environment:
      API_ADDRESS: predict_api
      API_PORT: 8000

networks:
  rakuten_mlops_network:
