services:

  api_data:
    build:
      context: src/data
      dockerfile: Dockerfile
    container_name: data_api
    networks: 
      - api_network
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data              
      - ./models:/app/models          
      - ./config:/app/config:ro       
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  api_train:
    build:
      context: src/train_model
      dockerfile: Dockerfile
    container_name: train_api
    networks: 
      - api_network
    ports:
      - "8002:8000"
    volumes:
      - ./data:/app/data:ro           
      - ./models:/app/models          
      - ./config:/app/config:ro 
      - ./results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  api_evaluate:
    build:
      context: src/evaluate_model
      dockerfile: Dockerfile
    container_name: evaluate_api
    networks: 
      - api_network
    ports:
      - "8004:8000"
    volumes:
      - ./data:/app/data:ro           
      - ./models:/app/models:ro       
      - ./results:/app/results        
      - ./config:/app/config:ro       
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      - MPLBACKEND=Agg

  api_predict:
    build:
      context: src/predict
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    container_name: predict_api
    networks: 
      - api_network
    ports:
      - "8000:8000" # TODO: remove port mapping (visibility from host) for production
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  test_api_predict:
    build: 
      context: tests/test_api_predict
      args:
        LOGDIR: /logs
    container_name: test_api_predict
    depends_on:
      api_predict:
        condition: service_healthy
      api_train:
        condition: service_healthy
      api_evaluate:
        condition: service_healthy
    networks: 
      - api_network
    volumes:
      - ./logs:/logs
    environment:
      API_ADDRESS: predict_api
      API_PORT: 8000

  nginx:
    build:
      context: deployments/nginx/
      dockerfile: Dockerfile
    container_name: nginx_reverse_proxy
    ports:
      - "8080:8080"
      - "8443:8443"
    networks: 
      - api_network
      - edge_network
      - monitoring_network
    depends_on:
      api_predict:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 3
  
  test_nginx:
    build:
      context: tests/test_nginx
      args:
        LOGDIR: /logs
    container_name: test_nginx
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      - edge_network
    volumes:
      - ./logs:/logs
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
    environment:
      NGINX_ADDRESS: nginx_reverse_proxy
      HTTPS_PORT: 8443
      HTTP_PORT: 8080
      REQUESTS_CA_BUNDLE: /etc/nginx/certs/nginx.crt

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./deployments/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.external-url=/prometheus/"
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./deployments/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring_network

networks:
  api_network:
    # internal network not exposed to host
    # internal: true
  edge_network:
    # network exposed to host for reverse proxy
  monitoring_network:
    # internal: true
    ipam:
      config:
        - subnet: 172.30.0.0/24
