services:

  api_predict:
    build:
      context: src/predict
      dockerfile: Dockerfile
    deploy:
      replicas: 1 # TODO: adjust replicas for production
    container_name: predict_api
    networks: 
      - rakuten_mlops_network
    expose:
      - "8000"
    ports:
      - "8000:8000" # TODO: remove port mapping (visibility from host) for production
    volumes:
      - ./models:/models
    environment:
      MODELS_DIR: /models
      MODEL_NAME: bert-rakuten-final
      # UV_TORCH_BACKEND: cpu  # seems not work as expected
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  test_api_predict:
    build: 
      context: tests/test_api_predict
      args:
        LOGDIR: /logs
    container_name: test_api_predict
    depends_on:
      api_predict:
        condition: service_healthy
    networks: 
      - rakuten_mlops_network
    volumes:
      - ./logs:/logs
    environment:
      API_ADDRESS: predict_api
      API_PORT: 8000

networks:
  rakuten_mlops_network:
