Paths: 
  data_raw_dir: "./src/data/raw/"
  image_train_path: "./src/data/raw/image_train/"
  image_train_path_output: "./src/data/preprocessed/image_train_preprocessed/"
  image_test_path_output: "./src/data/preprocessed/image_test_preprocessed/"
  X_train: "./src/data/raw/X_train_update.csv"
  y_train: "./src/data/raw/Y_train_CVw08PX.csv"
  TextOutlierReport: "./src/features/TextOutlierReport.txt"
  ImageDataFrameSavePath: "./src/data/tmp/"
  TextDataFrameSavePath: "./src/data/preprocessed/"
